[package]
name = "sha2"
version = "0.8.0"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
description = "SHA-2 hash functions"
documentation = "https://docs.rs/sha2"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "sha2", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = { git = "https://github.com/mesalock-linux/rustcrypto-traits-sgx", tag = "sgx_1.0.9" }
block-buffer = { git = "https://github.com/mesalock-linux/rustcrypto-utils-sgx", tag = "sgx_1.0.9" }
opaque-debug = "0.2"
fake-simd = "0.1"
sha2-asm = { version="0.5", optional = true }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk", optional = true, tag = "v1.0.9" }

[dev-dependencies]
#digest = { version = "0.8", features = ["dev"] }
#hex-literal = "0.1"

[features]
default = ["std", "mesalock_sgx"]
std = ["digest/std", "mesalock_sgx"]
asm = ["sha2-asm"]
mesalock_sgx = ["sgx_tstd"]

[badges]
travis-ci = { repository = "RustCrypto/hashes" }
